#!/bin/bash

# Used to cull media files from the device by reading them from .csv file
#
# Copyright (c) 2013, Eric Young. All rights reserved.
#

listName='/home/yantrauser/bin/media_list.csv'
baseDir='/opt/yantranet/agent/content'
total=0
culled=0
skipped=0

if [[ ! -e "$listName" ]]
then
  echo "Can't find the $listName you were looking for!"
  echo ""
  exit 99
else
  flip -u -v "$listName"
fi

cd $baseDir

while read -r culledFile
do
  total+=1  
  if [ -e "$culledFile" ]
  then
    echo
    echo "Found $culledFile"
    rm -f "$culledFile"

    if [ ! -e "$culledFile" ]
    then
      culled+=1
      echo "$culledFile has been deleted! Yay!!!"
    else
      skipped+=1
      echo "$culledFile still lives!!!!! Zombie!"
    fi

    elif [ ! -e "$culledFile" ]
    then
      echo "Didn't find $culledFile"
  fi
done < "$listName"

echo
echo "Summary:"
echo "--------"
echo 
echo "File list contained $total entries"
echo "$culled files were removed"
if [[ "$skipped" -gt "0" ]]
then
  echo "$skipped zombies live on"
fi
total=$total - $culled
echo "$total requests were ignored because they've already been removed"
echo