#!/bin/bash

# Can be used to stop and start ALL YantraNet related activities of a device
# including the agent itself.
#
# Copyright (c) 2013, Eric Young. All rights reserved.
#

# Test for su priv's
whoaminow() {
  if [ $(id -u) != "0" ] ; then
    echo "You must have superuser privileges to run this application"
    echo ""
	  exit 99
  fi
} # end whoaminow()

helpBlurb() {
  cat <<__EOF__

Usage is: sudo $0 [ -bfrsh] [ --basic] [ --full] [ --reverse] [ --start] [ --help]

$0 is a script that allow you to stop the YantraNet services and processes
quickly, easily and in a flexible manner. If invoked without any arguments, it
will assume the -b option.

  -b, --basic    Stops WebApp and AppMonitor for maintenance without video. 

  -f, --full     Stops WebApp, AppMonitor, Agent and AgentMonitor. Good for
                 mucking about without worrying about the services in use.
                 Restart is required after this argument because device 
                 can not communicate with YantraNet server.

  -r, --reverse  Tries to put all back the way it was. YMMV. Caveat emptor. 

  -s, --start    Starts the AppMonitor.

  -h, --help     Display this help and exit

__EOF__
} # end helpBlurb()

help() {
  # help is passed one argument: a 1 or a 2
  # 1 means to print help and continue where you left off.
  # 2 means to print help and exit
  if [ -z $1 ] ; then
    helpBlurb
    exit 1
  else
    case $1 in
      1 )
        helpBlurb
        break
      ;;
      2 | * )
        helpBlurb
        exit 0
    esac
  fi
} # end help()  

stopMonitor() {
  /etc/init.d/yantranet_agentMonitor.sh stop
} # end stopMonitor()
  
stopAgent() {
  /etc/init.d/yantranet_agent.sh stop
} # end stopAgent

stopAppMonitor() {
  killall -q AppMonitor
} # end stopAppMonitor()

stopWebApp() {
  killall -q WebApp
} # end stopWebApp

startMonitor() {
  /etc/init.d/yantranet_agentMonitor.sh start
} # end stopMonitor()
  
startAgent() {
  /etc/init.d/yantranet_agent.sh start
} # end stopAgent

startAppMonitor() {
  su - yantrauser <<__EOF__
  /opt/yantranet/agent/AppMonitor -db /opt/yantranet/agent/Agent.db
__EOF__
} # end stopAppMonitor()

################################################

whoaminow

if [[ $# -gt 1 ]]
then
  help
elif [[ $# -lt 1 ]]
then
  myArg="-b"
else
  myArg="$1"
fi  
   
case $myArg in
  -b | --basic )
    stopAppMonitor && sleep 1 && stopWebApp
    exit 0
  ;;
  -f | --full )
    stopAppMonitor && sleep 1 && stopWebApp && stopMonitor && stopAgent
    exit 0
  ;;
  -r | --reverse )
    startMonitor && sleep 35 && startAppMonitor
    exit 0
  ;;
  -s | --start )
    startAppMonitor
    exit 0
  ;;
  --help | * )
    help
esac
  